[build]
  command = "pnpm run build"
  publish = "dist/"

[build.environment]
  PNPM_VERSION = "9.0.5"

[[redirects]]
  from = "https://joelsmoney.com/*"
  to = "https://www.joelsmoney.com/:splat"
  status = 301
  force = true
